# Generated by Django 3.2.3 on 2021-06-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mycart',
        ),
    ]
