# Generated by Django 3.2.3 on 2021-06-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_carts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='quantity',
            field=models.IntegerField(default='1'),
        ),
    ]
