# Generated by Django 3.2.3 on 2021-06-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_placed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_placed',
            name='status',
        ),
    ]
